version: 2
build:
  os: ubuntu-20.04
  apt_packages:
    - libhts-dev
    - libssl-dev
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - requirements: docs/requirements.txt
    - path: .
