[tool.poetry]
name = "pyblat"
version = "0.1.0"
description = "A native python binding for blat suit"
authors = ["Yangyang Li <yangyang.li@northwestern.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.7.0"


[tool.ruff]
line-length = 120
extend-ignore = ["E501"]


[tool.poetry.scripts]
pyblatu = "pyblat.extc.update:cli"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-sugar = "^0.9.7"
pybind11 = "^2.10.4"
black = "^23.3.0"
ruff = "^0.0.263"
ipython = "^8.13.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
