[tool.poetry]
name = "pyblat"
version = "0.1.0"
description = "A native python binding for blat suit"
authors = ["Yangyang Li <yangyang.li@northwestern.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.7.0"
pybind11 = "^2.10.4"
setuptools = "^67.7.2"


[tool.ruff]
line-length = 120
extend-ignore = ["E501"]


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-sugar = "^0.9.7"
black = "^23.3.0"
ruff = "^0.0.263"
ipython = "^8.13.1"
pybind11-stubgen = "^0.13.0"
invoke = "^2.1.1"

[tool.poetry.build]
script = "build.py"
generate-setup-file=true

[build-system]
requires = ["pybind11>2.9.1", "poetry-core>=1.2.0", "setuptools>=40.6.0"]
build-backend = "poetry.core.masonry.api"
